# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: Skyrates
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxygen.cfg
    - GH_REPO_REF: github.com/temportalflux/Skyrates.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - echo "Building"
#  - make
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh

# Generate and deploy documentation
#after_success:
#  - cd $TRAVIS_BUILD_DIR
#  - chmod +x generateDocumentationAndDeploy.sh
#  - ./generateDocumentationAndDeploy.sh